kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: myds
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: mypod
      labels:
        app: web
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80