apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
  namespace: kube-system
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
      env: dev
  template:
    metadata:
      name: mypod
      labels:
        app: web
        env: dev
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPorts: 80
          